# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "arch20140620"
	config.vm.synced_folder ".", "/vagrant", type: "nfs"
	config.vm.network "private_network", type: "dhcp"
	config.vm.network "public_network", bridge: 'wlan0'
	#config.vm.network "forwarded_port", guest: 80, host: 8080
end
